channels:
- bioconda
- conda-forge

dependencies:
# base
- python=3.8.12

# python
- graphviz=2.50.0
- jupyter=1.0.0
- jupyter_contrib_nbextensions #=0.19.1
- matplotlib=3.4.3
- openpyxl=3.0.9
- pandas=1.3.4
- python-graphviz
- nb_conda_kernels=2.3.1
- nbformat
- pyyaml=6.0
- pygraphviz=1.7
- scipy=1.7.1
- seaborn=0.11.2
